#config_version=5

#
# ball_return.yaml
#
# Open the return gate and light the arrow (2 leds)
#
# Start on top lane center (row 2)
# Stop on ball end or outlane sw
#
#!!170424:VG:Creation
#!!170508:VG:Back to coil player, mpf issue fixed
#!!170509:VG:Add a timer before closing the gate when the outlane switch is hit
#
#
#

mode:
    start_events: shot_top_ro_2_hit
    stop_events: ball_ending, timer_ball_return_complete
    priority: 200


show_player:
    mode_ball_return_started:
        return_gate_open:
            speed: 1
    mode_ball_return_ended:
        return_gate_open:
            action: stop


coil_player:
    mode_ball_return_started:
        co_lower_right_gate: enable
    mode_ball_return_ended:
        co_lower_right_gate:
            action: disable


timers:
    ball_return:
        start_value: 0
        end_value: 3
        direction: up
        control_events:
            - event: sw_right_outlane_active
              action: start