#config_version=4

#
# ball_return.yaml
#
# Open the return gate and light the arrow (2 leds)
#
# Start on top lane center (row 2)
# Stop on ball end or outlane sw
#
#!!170424:VG:Creation
#
# TODO: can't make coil_player accept a command
#

mode:
    start_events: shot_top_ro_2_hit
    stop_events: ball_ending, sw_right_outlane_active
    priority: 200


show_player:
    mode_ball_return_started:
      return_gate_open:
        speed: 1
    mode_ball_return_ended:
      return_gate_open:
        action: stop


#coil_player:
#    #mode_ball_return_started: co_lower_right_gate # ok, but only a pulse...
#    mode_ball_return_started:
#        co_lower_right_gate: enable

#    #mode_ball_return_ended:
#        co_lower_right_gate:
#            action: disable

