#config_version=5

#
# Multiplier mode
#
#
#!!170502:Creation
#

mode:
    start_events: ball_started
    stop_events: ball_ending
    priority: 200


#
# Show list:
#  - get_2x_multiplier
#  - lit_2x_get3x_multiplier
#  - lit_3x_get5x_multiplier
#  - lit_5x_multiplier
#


show_player:
  mode_multiplier_started:
    get_2x_multiplier:
      speed: 1

  multiplier_2x_complete:
    get_2x_multiplier:
      action: stop
    lit_2X_multiplier:
      speed: 1
    get_3x_multiplier:
      speed: 1


  multiplier_3x_complete:
    lit_2X_multiplier:
      action: stop
    get_3x_multiplier:
      action: stop
    lit_3X_multiplier:
      speed: 1
    get_5x_multiplier:
      speed: 1

  multiplier_5x_complete:
    lit_3X_multiplier:
      action: stop
    get_5x_multiplier:
      action: stop
    lit_5X_multiplier:
      speed: 1


  mode_multiplier_stopped:
    get_2x_multiplier:
      action: stop
    get_3x_multiplier:
      action: stop
    get_5x_multiplier:
      action: stop
    lit_2X_multiplier:
      action: stop
    lit_3X_multiplier:
      action: stop
    lit_5X_multiplier:
      action: stop
