#config_version=5


show_player:
    mode_attract_started:
        attract_display_loop:
            speed: 1
        left_ramp: 
            speed: 2
            loop: -1
        top_row:
            speed: 2
            loop: -1
        drop_target:
            speed: 2
            loop: -1
        saucer:
            speed: 2
            loop: -1
        bonus:
            speed: 2
            loop: -1
        gate_open:
            speed: 10
            loop: -1
        open_gate:
            speed: 10
            loop: -1
        center_arrows:
            speed: 10
            loop: -1
        special:
            speed: 2
            loop: -1          

    mode_attract_stopped:
        attract_display_loop:
            action: stop
        left_ramp:
            action: stop
        top_row:
            action: stop
        drop_target:
            action: stop
        saucer:
            action: stop
        bonus:
            action: stop
        gate_open:
            action: stop
        open_gate:
            action: stop
        center_arrows:
            action: stop
        special:
            action: stop
