#config_version=4


show_player:
    mode_attract_started:
        attract_display_loop:
            speed: 1
        #stars_circle:
        #    speed: 4
        #    loop: -1
        #    #(color_on): green
        #bonus_ramp:
        #    speed: 4
        #    loop: -1
        #bumpers:
        #    speed : 4
        #    loop: -1
        left_ramp:
            speed: 2
            loop: -1
        top_row:
            speed: 2
            loop: -1
        drop_target:
            speed: 2
            loop: -1
        saucer:
            speed: 2
            loop: -1
        bonus:
            speed: 2
            loop: -1
        gate_open:
            speed: 10
            loop: -1
        center_arrows:
            speed: 10
            loop: -1
        special:
            speed: 2
            loop: -1          
