#config_version=4

mode:
    start_events: ball_starting
    priority: 100

slide_player:
    mode_base_started:
        widgets:
          - type: text
            text: (score)
            number_grouping: true
            min_digits: 2
            font_size: 20
            color: yellow
            anchor_y: top
            y: top
          - type: text
            text: PLAYER (number)
            x: 10
            y: bottom + 2
            font_size: 5
            anchor_x: left
            anchor_y: bottom
          - type: text
            text: BALL (ball)
            font_size: 5
            y: bottom + 2
            x: right - 10
            anchor_x: right
            anchor_y: bottom



scoring:
    #sw_spinner_active:
    shot_spinner_hit:
        score: 100
    sw_drop_target_e_active:
        score: 100
    sw_drop_target_d_active:
        score: 100
    sw_drop_target_c_active:
        score: 100
    sw_drop_target_b_active:
        score: 100
    sw_drop_target_a_active:
        score: 100
    sw_drop_target_rebound_active:
        score: 10
    sw_fix_target_right_1_active:
        score: 50
    sw_fix_target_right_2_active:
        score: 50
    sw_fix_target_right_3_active:
        score: 50
    sw_top_ro_button_active:
        score: 1000

    # shot_fix_target_center_hit:  #sw_fix_target_center_active:
    shot_fix_target_center_profile_just_lit_unlit_hit:
        score: 500
    shot_fix_target_center_profile_just_lit_lit_hit:
        score: 100

    sw_star_5_active:
        score: 25
    sw_star_4_active:
        score: 25
    sw_star_3_active:
        score: 25
    sw_star_2_active:
        score: 25
    sw_star_1_active:
        score: 25
    sw_right_slingshot_active:
        score: 25
    sw_left_slingshot_active:
        score: 25
    sw_bottom_bumper_active:
        score: 50
    sw_right_bumper_active:
        score: 50
    sw_left_bumper_active:
        score: 50
    sw_top_ro_1_active:
        score: 100
    sw_top_ro_2_active:
        score: 100
    sw_top_ro_3_active:
        score: 100
    sw_top_ro_4_active:
        score: 100
    sw_top_ro_5_active:
        score: 100
    top_ro_default_lit_complete:
        top_ro_default_lit_complete: 1



#    sw_left_flipper:
#        flip: -1
#    sw_right_flipper:
#        flip: 1


shot_groups:
    top_ro:
        shots: shot_top_ro_1, shot_top_ro_4, shot_top_ro_2, shot_top_ro_5, shot_top_ro_3
        rotate_left_events: sw_left_flipper
        rotate_right_events: sw_right_flipper
        reset_events:
            top_ro_default_lit_complete: 1s
            ball_starting: 0s
        enable_rotation_events: ball_started
        disable_rotation_events: ball_ending

    # when done : top_ro_default_lit_complete

# wait_for is mandatory....
#queue_relay_player:
#    top_ro_default_lit_complete{player.top_ro_default_lit_complete==1}:
#        post: enable_top_ro_mode_2
#        #wait_for: wizardintro_stopping
#    top_ro_default_lit_complete{player.top_ro_default_lit_complete==2}:
#        post: enable_top_ro_mode_3


logic_blocks:
    counters:
        enable_top_ro_mode_2:
            count_events: top_ro_default_lit_complete
            starting_count: 0
            count_complete_value: 1
            direction: up
            events_when_complete: enable_top_ro_mode_2_complete
        enable_top_ro_mode_3:
            #count_events: top_ro_default_lit_complete{current_player.enable_top_ro_mode_2_count==1}
            count_events: top_ro_default_lit_complete
            starting_count: 0
            count_complete_value: 2
            direction: up
            events_when_complete: enable_top_ro_mode_3_complete

