#config_version=4

mode:
    start_events: ball_starting
    priority: 100

slide_player:
    mode_base_started:
        widgets:
          - type: text
            text: (score)
            number_grouping: true
            min_digits: 2
            font_size: 100
          - type: text
            text: PLAYER (number)
            y: 10
            x: 10
            font_size: 50
            anchor_x: left
            anchor_y: bottom
          - type: text
            text: BALL (ball)
            y: 10
            x: right - 10
            anchor_x: right
            anchor_y: bottom
            font_size: 50
          - type: text
            text: "Pos: (flip)"
            y: 40%


scoring:
    sw_top_ro_1_active:
        score: 100
    sw_top_ro_2_active:
        score: 100
    sw_top_ro_3_active:
        score: 100
    sw_top_ro_4_active:
        score: 100
    sw_top_ro_5_active:
        score: 100

    sw_spinner:
        score: 1

    sw_drop_target_e:
        score: 100
    sw_drop_target_d:
        score: 100
    sw_drop_target_c:
        score: 100
    sw_drop_target_b:
        score: 100
    sw_drop_target_a:
        score: 100
    sw_drop_target_rebound:
        score: 10


    sw_fix_target_right_1:
        score: 50
    sw_fix_target_right_2:
        score: 50
    sw_fix_target_right_3:
        score: 50

    sw_top_ro_button:
        score: 1000

    sw_fix_target_center:
        score: 500

    sw_star_5:
        score: 25
    sw_star_4:
        score: 25
    sw_star_3:
        score: 25
    sw_star_2:
        score: 25
    sw_star_1:
        score: 25

    sw_right_slingshot:
        score: 25
    sw_left_slingshot:
        score: 25

    sw_bottom_bumper:
        score: 50
    sw_right_bumper:
        score: 50
    sw_left_bumper:
        score: 50



    sw_left_flipper:
        flip: -1
    sw_right_flipper:
        flip: 1

