#config_version=4

mode:
    start_events: ball_starting
    priority: 100

slide_player:
    mode_base_started:
        widgets:
          - type: text
            text: (score)
            number_grouping: true
            min_digits: 2
            font_size: 40
            color: yellow 
          - type: text
            text: PLAYER (number)
            y: 20
            x: 10
            font_size: 20
            anchor_x: left
            anchor_y: bottom
          - type: text
            text: BALL (ball)
            y: 20
            x: right - 10
            anchor_x: right
            anchor_y: bottom
            font_size: 20


scoring:
    #sw_spinner_active:
    shot_spinner_hit:
        score: 100
    sw_drop_target_e_active:
        score: 100
    sw_drop_target_d_active:
        score: 100
    sw_drop_target_c_active:
        score: 100
    sw_drop_target_b_active:
        score: 100
    sw_drop_target_a_active:
        score: 100
    sw_drop_target_rebound_active:
        score: 10
    sw_fix_target_right_1_active:
        score: 50
    sw_fix_target_right_2_active:
        score: 50
    sw_fix_target_right_3_active:
        score: 50
    sw_top_ro_button_active:
        score: 1000

    # shot_fix_target_center_hit:  #sw_fix_target_center_active:
    shot_fix_target_center_profile_just_lit_unlit_hit:
        score: 500
    shot_fix_target_center_profile_just_lit_lit_hit:
        score: 100

    sw_star_5_active:
        score: 25
    sw_star_4_active:
        score: 25
    sw_star_3_active:
        score: 25
    sw_star_2_active:
        score: 25
    sw_star_1_active:
        score: 25
    sw_right_slingshot_active:
        score: 25
    sw_left_slingshot_active:
        score: 25
    sw_bottom_bumper_active:
        score: 50
    sw_right_bumper_active:
        score: 50
    sw_left_bumper_active:
        score: 50
    sw_top_ro_1_active:
        score: 100
    sw_top_ro_2_active:
        score: 100
    sw_top_ro_3_active:
        score: 100
    sw_top_ro_4_active:
        score: 100
    sw_top_ro_5_active:
        score: 100



#    sw_left_flipper:
#        flip: -1
#    sw_right_flipper:
#        flip: 1


