#config_version=4
#
#!!170501:VG:adjust scoring
#

mode:
    start_events: ball_starting
    priority: 100
    code: base.base

slide_player:
    mode_base_started:
        widgets:
          - type: text
            text: (score)
            number_grouping: true
            min_digits: 2
            font_size: 20
            color: yellow
            anchor_y: top
            y: top
          - type: text
            text: (bonus_score)
            number_grouping: true
            min_digits: 4
            font_size: 5
            color: orange
            anchor_y: bottom
            y: bottom
          - type: text
            text: PLAYER (number)
            x: 10
            y: bottom + 2
            font_size: 5
            anchor_x: left
            anchor_y: bottom
          - type: text
            text: BALL (ball)
            font_size: 5
            y: bottom + 2
            x: right - 10
            anchor_x: right
            anchor_y: bottom


sound_player:
    sw_left_slingshot_active:
        snd_slingshot:
            action: play
    sw_right_slingshot_active:
        snd_slingshot:
            action: play

    sw_bottom_bumper_active:
        snd_bumper:
            action: play
    sw_right_bumper_active:
        snd_bumper:
            action: play
    sw_left_bumper_active:
        snd_bumper:
            action: play

    shot_spinner_hit:
        snd_spinner:
            action: play

    sw_drop_target_e_active:
        snd_drop_target:
            action: play
    sw_drop_target_d_active:
        snd_drop_target:
            action: play
    sw_drop_target_c_active:
        snd_drop_target:
            action: play
    sw_drop_target_b_active:
        snd_drop_target:
            action: play
    sw_drop_target_a_active:
        snd_drop_target:
            action: play

    sw_drop_target_rebound_active:
        snd_drop_target_rebound:
            action: play

    drop_target_bank_left_drops_down:
        snd_drop_target_all_down:
             action: play

    sw_fix_target_right_1_active:
        snd_fix_target:
            action: play
    sw_fix_target_right_2_active:
        snd_fix_target:
            action: play
    sw_fix_target_right_3_active:
        snd_fix_target:
            action: play

    sw_top_ro_button_active:
        snd_top_ro_button:
            action: play

    sw_top_ro_1_active:
        snd_top_ro_button:
            action: play
    sw_top_ro_2_active:
        snd_top_ro_button:
            action: play
    sw_top_ro_3_active:
        snd_top_ro_button:
            action: play
    sw_top_ro_4_active:
        snd_top_ro_button:
            action: play
    sw_top_ro_5_active:
        snd_top_ro_button:
            action: play

    top_ro_default_lit_complete:
        snd_top_ro_button_complete:
            action: play

    sw_feed_lane_active:
        snd_feed_lane:
            action: play

    sw_right_outlane_active:
        snd_outlane:
            action: play

    sw_left_outlane_active:
        snd_outlane:
            action: play

    sw_left_lane_ro_button_1_active:
        snd_left_lane:
            action: play
    sw_left_lane_ro_button_2_active:
        snd_left_lane:
            action: play
    sw_left_lane_ro_button_3_active:
        snd_left_lane:
            action: play
    sw_left_lane_ro_button_4_active:
        snd_left_lane:
            action: play
    sw_left_lane_ro_button_5_active:
        snd_left_lane:
            action: play

    #TODO: snd_saucer hide the snd_increase_bonus
    sw_saucer_active:
        snd_saucer:
            action: play
    multiplier_2x_complete:
        snd_increase_bonus:
            action: play
    multiplier_3x_complete:
        snd_increase_bonus:
            action: play
    multiplier_5x_complete:
        snd_increase_bonus:
            action: play



scoring:
    shot_spinner_hit:
        score: 100

    sw_drop_target_e_active:
        score: 300
    sw_drop_target_d_active:
        score: 300
    sw_drop_target_c_active:
        score: 300
    sw_drop_target_b_active:
        score: 300
    sw_drop_target_a_active:
        score: 300

    sw_drop_target_rebound_active:
        score: 10

    drop_target_bank_left_drops_down:
        score: 3000

    sw_fix_target_right_1_active:
        score: 300
    sw_fix_target_right_2_active:
        score: 300
    sw_fix_target_right_3_active:
        score: 300

    sw_top_ro_button_active:
        score: 300

    # shot_fix_target_center_hit:  #sw_fix_target_center_active:
    shot_fix_target_center_profile_just_lit_unlit_hit:
        score: 500
    shot_fix_target_center_profile_just_lit_lit_hit:
        score: 100

    sw_right_slingshot_active:
        score: 10
    sw_left_slingshot_active:
        score: 10

    sw_bottom_bumper_active:
        score: 10
    sw_right_bumper_active:
        score: 10
    sw_left_bumper_active:
        score: 10

    sw_top_ro_1_active:
        score: 300
    sw_top_ro_2_active:
        score: 300
    sw_top_ro_3_active:
        score: 300
    sw_top_ro_4_active:
        score: 300
    sw_top_ro_5_active:
        score: 300

    top_ro_default_lit_complete:
        score: 3000

    sw_feed_lane_active:
        score: 300

    sw_fix_target_center:
        score: 300

    sw_right_outlane_active:
        score: 1000

    sw_left_outlane_active:
        score: 1000

    sw_saucer_active:
        score: 3000

    sw_left_lane_ro_button_1_active:
        score: 100
    sw_left_lane_ro_button_2_active:
        score: 100
    sw_left_lane_ro_button_3_active:
        score: 100
    sw_left_lane_ro_button_4_active:
        score: 100
    sw_left_lane_ro_button_5_active:
        score: 100

    game_starting:
        multiplier: 1
    multiplier_2x_complete:
        multiplier: 1
        #action: set
    multiplier_3x_complete:
        multiplier: 1
        #action: set
    multiplier_5x_complete:
        multiplier: 2
        #action: set

    increase_bonus:
        bonus_score: 1000

# doesn't work
#    ball_ended:
#        bonus_score: 0|set

# never called ?
#    ball_started:
#        bonus_score:
#            score: 0
#            action: set

# ok
    sw_right_flipper_hit:
        bonus_score:
            score: 0
            action: set

# ok
#    mode_base_started:
#        bonus_score:
#            score: 0
#            action: set

    bonus_score_reset:
        bonus_score:
            score: 0
            action: set

#    sw_left_flipper:
#        flip: -1
#    sw_right_flipper:
#        flip: 1

event_player:
    ball_started: bonus_score_reset
    #bonus_score_reset: ball_started

shots:
    saucer_shot:
        switch: sw_saucer
        # accept only if the saucer has not been activated in the last second
        delay_switch:
            sw_saucer: 1s


shot_groups:
    top_ro:
        shots: shot_top_ro_1, shot_top_ro_4, shot_top_ro_2, shot_top_ro_5, shot_top_ro_3
        rotate_left_events: sw_left_flipper
        rotate_right_events: sw_right_flipper
        reset_events:
            top_ro_default_lit_complete: 1s
            ball_starting: 0s
        enable_rotation_events: ball_started
        disable_rotation_events: ball_ending


logic_blocks:
    counters:
        enable_top_ro_mode_2:
            count_events: top_ro_default_lit_complete
            starting_count: 0
            count_complete_value: 1
            direction: up
            events_when_complete: enable_top_ro_mode_2_complete
            persist_state: true
        enable_top_ro_mode_3:
            #count_events: top_ro_default_lit_complete{current_player.enable_top_ro_mode_2_count==1}
            count_events: top_ro_default_lit_complete
            starting_count: 0
            count_complete_value: 2
            direction: up
            events_when_complete: enable_top_ro_mode_3_complete
            persist_state: true

        enable_dropbank_lit_extraball:
            count_events: drop_target_bank_left_drops_down
            starting_count: 0
            count_complete_value: 1
            direction: up
            events_when_complete: lit_extraball

        enable_dropbank_mode_special:
            count_events: drop_target_bank_left_drops_down
            starting_count: 0
            count_complete_value: 2
            direction: up
            events_when_complete: win_extraball, lit_special

        multiplier_2x:
            count_events: saucer_shot_hit
            starting_count: 0
            count_complete_value: 1
            direction: up
            events_when_complete: multiplier_2x_complete

        multiplier_3x:
            count_events: saucer_shot_hit
            starting_count: 0
            count_complete_value: 2
            direction: up
            events_when_complete: multiplier_3x_complete

        multiplier_5x:
            count_events: saucer_shot_hit
            starting_count: 0
            count_complete_value: 3
            direction: up
            events_when_complete: multiplier_5x_complete


show_player:
    ball_drain:
      end_ball_show:
        speed: 1
        loops: 0
        show_tokens:
          all: led
          led: bonus

