#config_version=4

#
# Bonus mode
#
#
#!!170509:Creation
# https://github.com/missionpinball/mpf-examples/blob/4a7c04c1a50e3ca7fdbe3dfbf45ff2818feaecd9/demo_man/modes/bonus/config/bonus.yaml
#

mode:
    priority: 300

mode_settings:
    display_delay_ms: 3s
    keep_multiplier: False
    bonus_entries:
        - event: show_bonus_score
          score: 1
          player_score_entry: bonus_score # score ok
          reset_player_score_entry: True

scoring:
    bonus_start:
        bonus_subtotal:
            score: 0
            action: set
    bonus_subtotal:
        bonus_subtotal: bonus_score
    bonus_multiplier:
        bonus_subtotal:
           #score: bonus_score * multiplier #NOK
           score: bonus_score * current_player.bonus_multiplier #NOK, always 0
           action: set



show_player:
    bonus_start:
        bonus_display:
            speed: 1
            loops: 0
    bonus_multiplier:
        bonus_multiplier:
            speed: 1
            loops: 0
    bonus_subtotal:
        bonus_subtotal:
            speed: 1
            loops: 0
    bonus_total:
        bonus_total:
            speed: 1
            loops: 0

