#config_version=4

#
# Bonus mode
#
#
#!!170509:Creation
# https://github.com/missionpinball/mpf-examples/blob/4a7c04c1a50e3ca7fdbe3dfbf45ff2818feaecd9/demo_man/modes/bonus/config/bonus.yaml
#

mode:
    #start_events: ball_started
    #stop_events: ball_ending
    priority: 300

mode_settings:
    bonus_entries:
        - event: show_bonus_score
          score: 0
#        - event: add_bonus_score
#          score: bonus_score
#          player_score_entry: multiplier
#        - event: show_total_score
#          score: 0

show_player:
    bonus_start:
        bonus_display:
            speed: 1
            loops: 0
    bonus_multiplier:
        bonus_multiplier:
            speed: 1
            loops: 0
    bonus_subtotal:
        bonus_subtotal:
            speed: 1
            loops: 0
    bonus_total:
        bonus_total:
            speed: 1
            loops: 0

scoring:
    bonus_total: # ok
        score: (bonus_score)
#        test5_score: 100
#        test_score: (player_bonus_score)
#        test2_score: player_bonus_score
#        test3_score: (bonus_score)
#        test4_score: bonus_score
#    mode_bonus_stopping: # ok
#        bonus_score:
#            score: 0
#            action: set


#event_player:
#    bonus_mode_started: bonus_score_reset # ok
