#config_version=4

coils:
    co_outhole_kicker:
        number: 1

    co_knocker:
        number: 2

    co_saucer:
        number: 3

    co_left_bumper:
        number: 4
    co_left_bumper:
        number: 5
    co_bottom_bumper:
        number: 6

    co_left_slingshot:
        number: 7
    co_right_slingshot:
        number: 8

    co_drop_targer_reset:
        number: 9
    co_lower_right_gate:
        number: 10

    #co_coin_lockout_door:
    #    number: 11
    #relay_flipper_enable:
    #    number: 12

    co_left_flipper_main:
        number: 50
    co_left_flipper_hold:
        number: 51
        allow_enable: true
    co_right_flipper_main:
        number: 52
    co_right_flipper_hold:
        number: 53
        allow_enable: true

        
