#config_version=5

coils:
    co_outhole_kicker:
        number: 42
        default_pulse_ms: 30

# TODO:
#    co_knocker:
#        number: 0

    co_saucer:
        number: 26
        default_pulse_ms: 30

    co_left_bumper:
        number: 46
        default_pulse_ms: 50
    co_right_bumper:
        number: 30
        default_pulse_ms: 50
    co_bottom_bumper:
        number: 32
        default_pulse_ms: 50

    co_left_slingshot:
        number: 44
        default_pulse_ms: 50
    co_right_slingshot:
        number: 28
        default_pulse_ms: 50

    co_drop_targer_reset:
        number: 36
        default_pulse_ms: 30

    co_lower_right_gate:
        number: 34
        allow_enable: true

    #co_coin_lockout_door:
    #    number: 11

    #relay_flipper_enable:
    #    number: 12

    co_left_flipper_main:
        number: 40
    co_right_flipper_main:
        number: 38

        
