#config_version=4

coils:
    co_outhole_kicker:
        number: 42

    co_knocker:
        number: 0

    co_saucer:
        number: 26

    co_left_bumper:
        number: 46
    co_right_bumper:
        number: 30
    co_bottom_bumper:
        number: 32

    co_left_slingshot:
        number: 44
    co_right_slingshot:
        number: 28

    co_drop_targer_reset:
        number: 36
    co_lower_right_gate:
        number: 34

    #co_coin_lockout_door:
    #    number: 11
    #relay_flipper_enable:
    #    number: 12

    co_left_flipper_main:
        number: 50
    co_left_flipper_hold:
        number: 51
        allow_enable: true
    co_right_flipper_main:
        number: 52
    co_right_flipper_hold:
        number: 53
        allow_enable: true

        
