#config_version=4

config:
    - switchs.yaml
    - leds.yaml
    - coils.yaml
    - hardware.yaml
    - keyboard.yaml
    - rasppinball.yaml
    - shots.yaml
    - display.yaml
    - sounds.yaml

#bcp:
#    servers:
#       ip: None

#kivy_config:
#    graphics:
#        fbo: force-hardware

mpf:
  default_pulse_ms: 50


player_vars:
    bonus_multiplier:
        initial_value: 1


modes:
  - attract
  - base
  - bonus
  - spinner_1k
  - open_gate
  - ball_return
  - toprow_lites_center
  - toprow_lites_jet_stream
  - multiplier

