#config_version=4

config:
    - switchs.yaml
    - leds.yaml
    - coils.yaml
    - hardware.yaml
    - keyboard.yaml
    - rasppinball.yaml

displays:
    window:
        #width: 1280
        #height: 800
        width: 640
        height: 400

window:
    #width: 1280
    #height: 800
    width: 640
    height: 400
    title: Supersonic pinball prototype
    resizable: false
    #fullscreen: auto
    #borderless: false
    exit_on_escape: true

#kivy_config:
#    graphics:
#        fbo: force-hardware


slides:
    welcome_slide:
        widgets:
          - type: text
            text: Super SONIC !
            font_size: 50
            color: orange
          - type: rectangle
            width: 320
            height: 60
    #attract_started:
    #    widgets:
    #      - text: ATTRACT MODE
    #        type: text
    ball_started:
        widgets:
          - type: text
            text: PLAYER (number) BALL (ball)

slide_player:
    init_done: welcome_slide
    #mode_attract_started: attract_started
    #ball_started: ball_started


modes:
  - base
  - attract


shots:
    shot_fix_target_center:
        switch: sw_fix_target_center
        show_tokens:
            led: ld_not_used_1
        profile: profile_just_lit


    shot_drop_target_e:
        switch: sw_drop_target_e
    shot_drop_target_d:
        switch: sw_drop_target_d
    shot_drop_target_c:
        switch: sw_drop_target_c
    shot_drop_target_b:
        switch: sw_drop_target_b
    shot_drop_target_a:
        switch: sw_drop_target_a

    shot_top_ro_5:
        switch: sw_top_ro_5
        show_tokens:
            led: ld_top_lane_5
    shot_top_ro_4:
        switch: sw_top_ro_4
        show_tokens:
            led: ld_top_lane_4
    shot_top_ro_3:
        switch: sw_top_ro_3
        show_tokens:
            led: ld_top_lane_3
    shot_top_ro_2:
        switch: sw_top_ro_2
        show_tokens:
            led: ld_top_lane_2
    shot_top_ro_1:
        switch: sw_top_ro_1
        show_tokens:
            led: ld_top_lane_1

shot_groups:
    top_ro:
        shots: shot_top_ro_1, shot_top_ro_4, shot_top_ro_2, shot_top_ro_5, shot_top_ro_3
        rotate_left_events: sw_left_flipper
        rotate_right_events: sw_right_flipper
        reset_events:
            top_ro_default_lit_complete: 1s
            ball_starting: 0s
        enable_rotation_events: ball_started
        disable_rotation_events: ball_ending


drop_targets:
    e:
        switch: sw_drop_target_e
    d:
        switch: sw_drop_target_d
    c:
        switch: sw_drop_target_c
    b:
        switch: sw_drop_target_b
    a:
        switch: sw_drop_target_a


drop_target_banks:
    left_drops:
        drop_targets: a, b, c, d, e
        reset_coils: co_drop_targer_reset
        reset_events:
            ball_starting: 0s
            drop_target_bank_left_drops_down: 1s
            reset_left_drops: 0s



shot_profiles:
    profile_fix_target_center:
        states:
          - name: unlit
            show: off
          - name: flashing
            show: flash
          - name: lit
            show: on
        loop: yes
    profile_just_lit:
        states:
          - name: unlit
            show: off
          - name: lit
            show: on
        loop: no

