#config_version=4

config:
    - switchs.yaml
    - leds.yaml
    - coils.yaml
    - hardware.yaml
    - keyboard.yaml

displays:
    window:
        #width: 1280
        #height: 800
        width: 640
        height: 400

window:
    #width: 1280
    #height: 800
    width: 640
    height: 400
    title: Supersonic pinball prototype
    resizable: false
    #fullscreen: auto
    #borderless: false
    exit_on_escape: true

#kivy_config:
#    graphics:
#        fbo: force-hardware


slides:
    welcome_slide:
        widgets:
          - type: text
            text: Super SONIC !
            font_size: 50
            color: orange
          - type: rectangle
            width: 320
            height: 60
    #attract_started:
    #    widgets:
    #      - text: ATTRACT MODE
    #        type: text
    ball_started:
        widgets:
          - type: text
            text: PLAYER (number) BALL (ball)

slide_player:
    init_done: welcome_slide
    #mode_attract_started: attract_started
    #ball_started: ball_started


modes:
  - base
  - attract


shots:
    shot_fix_target_center:
        switch: sw_fix_target_center
        show_tokens:
            led: ld_not_used_1
        profile: profile_just_lit

shot_profiles:
    profile_fix_target_center:
        states:
          - name: unlit
            show: off
          - name: flashing
            show: flash
          - name: lit
            show: on
        loop: yes
    profile_just_lit:
        states:
          - name: unlit
            show: off
          - name: lit
            show: on
        loop: no

