#config_version=4

config:
    - switchs.yaml
    - leds.yaml
    - coils.yaml
    - hardware.yaml
    - keyboard.yaml
    - rasppinball.yaml
    - shots.yaml
    - display.yaml

#bcp:
#    servers:
#       ip: None

kivy_config:
    graphics:
        fbo: force-hardware




modes:
  - base
  - attract

