#config_version=5

#!!181124:VG:Added logging.yaml

config:
    - switchs.yaml
    - leds.yaml
    - coils.yaml
    - hardware.yaml
    - keyboard.yaml
    - rasppinball.yaml
#    - shots.yaml
    - display.yaml
    - logging.yaml

#bcp:
#    servers:
#       ip: None

#kivy_config:
#    graphics:
#        fbo: force-hardware

mpf:
  default_pulse_ms: 50


modes:
  - attract
  - base