#config_version=5

flippers:
    left_flipper:
        main_coil: co_left_flipper_main
        activation_switch: bt_left_flipper

    right_flipper:
        main_coil: co_right_flipper_main
        activation_switch: bt_right_flipper

playfields:
    playfield:
        default_source_device: bd_trough
        tags: default

ball_devices:
    bd_trough:
        ball_switches: sw_outhole
        eject_coil: co_outhole_kicker
        tags: trough, home, drain
        entrance_count_delay: 300ms #??
        #exit_delay_count: 300ms
        debug: yes
        #eject_targets: playfield

    bd_bonus_hole:
        ball_switches: sw_saucer
        eject_coil: co_saucer
        eject_timeouts: 1s


autofire_coils:
    left_slingshot:
        coil: co_left_slingshot
        switch: sw_left_slingshot
    right_slingshot:
        coil: co_right_slingshot
        switch: sw_right_slingshot
    left_bumber:
        coil: co_left_bumper
        switch: sw_left_bumper
    right_bumber:
        coil: co_right_bumper
        switch: sw_right_bumper
    bottom_bumber:
        coil: co_bottom_bumper
        switch: sw_bottom_bumper


virtual_platform_start_active_switches:
    -  sw_outhole  # put a ball ready to go at the beginning


drop_targets:
    e:
        switch: sw_drop_target_e
    d:
        switch: sw_drop_target_d
    c:
        switch: sw_drop_target_c
    b:
        switch: sw_drop_target_b
    a:
        switch: sw_drop_target_a


drop_target_banks:
    left_drops:
        drop_targets: a, b, c, d, e
        reset_coils: co_drop_targer_reset
        reset_events:
            ball_starting: 0s
            drop_target_bank_left_drops_down: 1s
            reset_left_drops: 0s



shot_profiles:
    profile_fix_target_center:
        states:
          - name: unlit
            show: off
          - name: flashing
            show: flash
          - name: lit
            show: on
        loop: yes
    profile_just_lit:
        states:
          - name: unlit
            show: off
          - name: lit
            show: on
        loop: no
