#config_version=4

flippers:
    left_flipper:
        main_coil: co_left_flipper_main
        activation_switch: bt_left_flipper

    right_flipper:
        main_coil: co_right_flipper_main
        activation_switch: bt_right_flipper


ball_devices:
    bd_trough:
        ball_switches: sw_outhole
        eject_coil: co_outhole_kicker
        tags: trough, home, drain, ball_add_live
        entrance_count_delay: 300ms #??
        #exit_delay_count: 300ms
        debug: yes
        #eject_targets: playfield

    bd_bonus_hole:
        ball_switches: sw_saucer
        eject_coil: co_saucer
        eject_timeouts: 1s


autofire_coils:
    left_slingshot:
        coil: co_left_slingshot
        switch: sw_left_slingshot
    right_slingshot:
        coil: co_right_slingshot
        switch: sw_right_slingshot
    left_bumber:
        coil: co_left_bumper
        switch: sw_left_bumper
    right_bumber:
        coil: co_right_bumper
        switch: sw_right_bumper
    bottom_bumber:
        coil: co_bottom_bumper
        switch: sw_bottom_bumper


diverters:
    ball_return_diverter:
        enable_events: mode_ball_return_started
        disable_events: mode_ball_return_stopped
        activation_coil: co_lower_right_gate
        activation_switches: sw_right_outlane
        activation_time: 3s
        type: hold


virtual_platform_start_active_switches:
    -  sw_outhole  # put a ball ready to go at the beginning
