#config_version=4

flippers:
    left_flipper:
        main_coil: co_left_flipper_main
        hold_coil: co_left_flipper_hold
        activation_switch: bt_left_flipper

    right_flipper:
        main_coil: co_right_flipper_main
        hold_coil: co_right_flipper_hold
        activation_switch: bt_right_flipper


