#config_version=4

#platform:

flippers:
    left_flipper:
        main_coil: co_left_flipper_main
        hold_coil: co_left_flipper_hold
        activation_switch: bt_left_flipper
        #enable_events: machine_reset_phase_3

    right_flipper:
        main_coil: co_right_flipper_main
        hold_coil: co_right_flipper_hold
        activation_switch: bt_right_flipper
        #enable_events: machine_reset_phase_3


ball_devices:
    bd_trough:
        ball_switches: sw_outhole
        eject_coil: co_outhole_kicker
        tags: trough, home, drain, ball_add_live
        entrance_count_delay: 300ms #??
        #exit_delay_count: 300ms
        debug: yes
        #eject_targets: playfield



autofire_coils:
    left_slingshot:
        coil: co_left_slingshot
        switch: sw_left_slingshot
    right_slingshot:
        coil: co_right_slingshot
        switch: sw_right_slingshot
    left_bumber:
        coil: co_left_bumper
        switch: sw_left_bumper
    right_bumber:
        coil: co_right_bumper
        switch: sw_right_bumper
    bottom_bumber:
        coil: co_bottom_bumper
        switch: sw_bottom_bumper



virtual_platform_start_active_switches:
    sw_outhole  # put a ball ready to go at the beginning
