#config_version=5

hardware:
    platform: rasppinball
    #debug: true
    #driverboards: rasp

#bcp:
#    servers:
#        ip: None

#rasppinball:
#    debug: false
#    #rasp_strip_leds:      #   LED strip configuration:
#    #    strip_0:
#    count: 64         #   Number of LED pixels.
#    pin: 18           #   GPIO pin connected to the pixels (must support PWM!).
#    freq: 800000      #   LED signal frequency in hertz (usually 800khz)
#    dma:  1           #   DMA channel to use for generating signal (try 5)
#    brightness: 255   #   Set to 0 for darkest and 255 for brightest
#    invert: false     #   True to invert the signal (when using NPN transistor level shift)


