#config_version=5


mode:
    start_events: enable_top_ro_mode_2_complete
    stop_events: ball_ending
    priority: 200


#show_player:
#    mode_toprow_lites_jet_stream_started:
#        left_ramp:
#            loop: -1
#
#    mode_toprow_lites_jet_stream_stopped:
#        left_ramp:
#            action: stop


shots:
    lit_left_lane_ro_1_shot:
        switch: sw_top_ro_1
        show_tokens:
            led: ld_left_lane_1
    lit_left_lane_ro_2_shot:
        switch: sw_top_ro_2
        show_tokens:
            led: ld_left_lane_2
    lit_left_lane_ro_3_shot:
        switch: sw_top_ro_3
        show_tokens:
            led: ld_left_lane_3
    lit_left_lane_ro_4_shot:
        switch: sw_top_ro_4
        show_tokens:
            led: ld_left_lane_4
    lit_left_lane_ro_5_shot:
        switch: sw_top_ro_5
        show_tokens:
            led: ld_left_lane_5

event_player:
    sw_left_lane_ro_button_1_active{current_player.left_lane_ro_1_state_count==1}: increase_bonus
    sw_left_lane_ro_button_2_active{current_player.left_lane_ro_2_state_count==1}: increase_bonus
    sw_left_lane_ro_button_3_active{current_player.left_lane_ro_3_state_count==1}: increase_bonus
    sw_left_lane_ro_button_4_active{current_player.left_lane_ro_4_state_count==1}: increase_bonus
    sw_left_lane_ro_button_5_active{current_player.left_lane_ro_5_state_count==1}: increase_bonus


counters:
    left_lane_ro_1_state:
        count_events: sw_top_ro_1_active
        starting_count: 0
        count_complete_value: 1
        direction: up
        reset_on_complete: false
        disable_on_complete: true

    left_lane_ro_2_state:
        count_events: sw_top_ro_2_active
        starting_count: 0
        count_complete_value: 1
        direction: up
        reset_on_complete: false
        disable_on_complete: true

    left_lane_ro_3_state:
        count_events: sw_top_ro_3_active
        starting_count: 0
        count_complete_value: 1
        direction: up
        reset_on_complete: false
        disable_on_complete: true

    left_lane_ro_4_state:
        count_events: sw_top_ro_4_active
        starting_count: 0
        count_complete_value: 1
        direction: up
        reset_on_complete: false
        disable_on_complete: true

    left_lane_ro_5_state:
        count_events: sw_top_ro_5_active
        starting_count: 0
        count_complete_value: 1
        direction: up
        reset_on_complete: false
        disable_on_complete: true