#config_version=5

#
# toprow_lites_center
#
# Spinner bonus is enabled, lit or blink the spinner led
#
# Start when the top lane row 2 (center) is activated
# Stop on ball loose
#
#!!170428:FIX:the block scoring doesn't work and cumulate base mode...
#!!170501:FIXED:issue with star lit
#!!170501:FIXED:show player conflicts with lit star for scoring...
#!!170502:light and scoring fixed
#         see https://groups.google.com/forum/#!topic/mpf-users/RmOsYkKyc8M, thanks to Dan !

mode:
    start_events: ball_started
    stop_events: ball_ending
    priority: 200


#show_player:
#    mode_toprow_lites_center_started:
#        stars_circle:
#            loop: -1
#
#    mode_toprow_lites_center_stopped:
#        stars_circle:
#            action: stop


#
# top row corridors lit center stars
#
shots:
    lit_star_1_shot:
        switch: sw_top_ro_1
        show_tokens:
            led: ld_star_1
    lit_star_2_shot:
        switch: sw_top_ro_2
        show_tokens:
            led: ld_star_2
    lit_star_3_shot:
        switch: sw_top_ro_3
        show_tokens:
            led: ld_star_3
    lit_star_4_shot:
        switch: sw_top_ro_4
        show_tokens:
            led: ld_star_4
    lit_star_5_shot:
        switch: sw_top_ro_5
        show_tokens:
            led: ld_star_5


#
# center star score 100 when unlit, 1000 when lit
#

event_player:
    sw_star_1_active{current_player.star_1_state_count==1}: increase_bonus
    sw_star_2_active{current_player.star_2_state_count==1}: increase_bonus
    sw_star_3_active{current_player.star_3_state_count==1}: increase_bonus
    sw_star_4_active{current_player.star_4_state_count==1}: increase_bonus
    sw_star_5_active{current_player.star_5_state_count==1}: increase_bonus



counters:
    star_1_state:
        count_events: sw_top_ro_1_active
        starting_count: 0
        count_complete_value: 1
        direction: up
        reset_on_complete: false
        disable_on_complete: true

    star_2_state:
        count_events: sw_top_ro_2_active
        starting_count: 0
        count_complete_value: 1
        direction: up
        reset_on_complete: false
        disable_on_complete: true

    star_3_state:
        count_events: sw_top_ro_3_active
        starting_count: 0
        count_complete_value: 1
        direction: up
        reset_on_complete: false
        disable_on_complete: true

    star_4_state:
        count_events: sw_top_ro_4_active
        starting_count: 0
        count_complete_value: 1
        direction: up
        reset_on_complete: false
        disable_on_complete: true

    star_5_state:
        count_events: sw_top_ro_5_active
        starting_count: 0
        count_complete_value: 1
        direction: up
        reset_on_complete: false
        disable_on_complete: true


